"""Build the icon and logo files from the owner's artwork in assets/.

    QT_QPA_PLATFORM=offscreen python tools_make_assets.py

Sources (the owner's artwork):
- assets/kanzonas-mark-source.png  cactus + sunflower
- assets/kanzonas-logo-source.png  the owner's full logo (Help > About)
The app icon is a red tile (the color people associate with PDF apps) with a white page
holding the cactus and sunflower, drawn here as vectors so it is sharp at every size; sizes
16-32 use a simpler page without the folded corner. Outputs: kanzonas.ico, kanzonas.png,
installer BMPs and the embedded copy kanzonas/branding_data.py.
"""
import base64
import io
import sys

from PIL import Image
from PySide6.QtCore import QBuffer, QRectF, Qt
from PySide6.QtGui import QColor, QImage, QLinearGradient, QPainter, QPainterPath
from PySide6.QtWidgets import QApplication

app = QApplication(sys.argv)
mark = QImage("assets/kanzonas-mark-source.png")


RED_TOP, RED_BOTTOM = "#e0362c", "#a3120f"      # red tile: the color people link with PDFs


def _tile(p, size_units, radius):
    g = QLinearGradient(0, 0, 0, size_units)
    g.setColorAt(0, QColor(RED_TOP))
    g.setColorAt(1, QColor(RED_BOTTOM))
    p.setPen(Qt.NoPen)
    p.setBrush(g)
    m = size_units / 64
    p.drawRoundedRect(QRectF(m, m, size_units - 2 * m, size_units - 2 * m), radius, radius)


def big_icon(size=512):
    """Red tile; a white page with a folded corner holds the owner's cactus and sunflower."""
    img = QImage(size, size, QImage.Format_ARGB32_Premultiplied)
    img.fill(Qt.transparent)
    p = QPainter(img)
    p.setRenderHint(QPainter.Antialiasing)
    p.setRenderHint(QPainter.SmoothPixmapTransform)
    p.scale(size / 256.0, size / 256.0)
    _tile(p, 256, 44)
    x0, y0, x1, y1, f = 52, 30, 204, 226, 34
    page = QPainterPath()
    page.moveTo(x0 + 10, y0)
    page.lineTo(x1 - f, y0)
    page.lineTo(x1, y0 + f)
    page.lineTo(x1, y1 - 10)
    page.quadTo(x1, y1, x1 - 10, y1)
    page.lineTo(x0 + 10, y1)
    page.quadTo(x0, y1, x0, y1 - 10)
    page.lineTo(x0, y0 + 10)
    page.quadTo(x0, y0, x0 + 10, y0)
    p.setBrush(QColor(0, 0, 0, 60))                    # soft shadow
    p.drawPath(page.translated(3, 4))
    p.setBrush(QColor("white"))
    p.drawPath(page)
    fold = QPainterPath()
    fold.moveTo(x1 - f, y0)
    fold.lineTo(x1 - f, y0 + f)
    fold.lineTo(x1, y0 + f)
    fold.closeSubpath()
    p.setBrush(QColor("#d9d9d9"))
    p.drawPath(fold)
    h = 150.0
    w = h * mark.width() / mark.height()
    p.drawImage(QRectF(128 - w / 2, 62, w, h), mark)
    p.end()
    return img


def small_icon(size=128):
    """16-32 px: the red tile and a plain white page (a folded corner is too fine there)."""
    img = QImage(size, size, QImage.Format_ARGB32_Premultiplied)
    img.fill(Qt.transparent)
    p = QPainter(img)
    p.setRenderHint(QPainter.Antialiasing)
    p.setRenderHint(QPainter.SmoothPixmapTransform)
    p.scale(size / 128.0, size / 128.0)
    _tile(p, 128, 24)
    p.setBrush(QColor("white"))
    p.drawRoundedRect(QRectF(22, 12, 84, 104), 10, 10)
    h = 92.0
    w = h * mark.width() / mark.height()
    p.drawImage(QRectF(64 - w / 2, 18, w, h), mark)
    p.end()
    return img


def to_pil(qimg):
    buf = QBuffer()
    buf.open(QBuffer.ReadWrite)
    qimg.save(buf, "PNG")
    return Image.open(io.BytesIO(bytes(buf.data()))).convert("RGBA")


big = to_pil(big_icon())
small = to_pil(small_icon())
big.save("assets/kanzonas-icon-source.png")
small.save("assets/kanzonas-icon-small-source.png")
sizes = [16, 20, 24, 32, 40, 48, 64, 128, 256]
frames = {s: (small if s <= 32 else big).resize((s, s), Image.LANCZOS) for s in sizes}
frames[256].save("assets/kanzonas.png")
frames[256].save("assets/kanzonas.ico", sizes=[(s, s) for s in sizes],
                 append_images=[frames[s] for s in sizes[:-1]])


def on_white(w, h, size, pos):
    bg = Image.new("RGB", (w, h), "white")
    im = big.resize((size, size), Image.LANCZOS)
    bg.paste(im, pos, im)
    return bg


on_white(164, 314, 150, (7, 80)).save("assets/wizard-large.bmp")
on_white(55, 55, 51, (2, 2)).save("assets/wizard-small.bmp")


def b64(path):
    data = base64.b64encode(open(path, "rb").read()).decode()
    return "\n".join(f'    "{data[i:i + 96]}"' for i in range(0, len(data), 96))


with open("kanzonas/branding_data.py", "w") as f:
    f.write('"""Generated by tools_make_assets.py from assets/: do not edit."""\n\nimport base64\n\n')
    f.write(f"ICON = base64.b64decode(\n{b64('assets/kanzonas-icon-source.png')}\n)\n\n")
    f.write(f"ICON_SMALL = base64.b64decode(\n{b64('assets/kanzonas-icon-small-source.png')}\n)\n\n")
    f.write(f"LOGO = base64.b64decode(\n{b64('assets/kanzonas-logo-source.png')}\n)\n")
print("assets written")
